// <auto-generated />
using APIpetshop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIpetshop.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20230709042933_Azure")]
    partial class Azure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIpetshop.Models.ClienteCompra", b =>
                {
                    b.Property<int>("idCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCompra"));

                    b.Property<string>("cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codigoCompra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("valorCompra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idCompra");

                    b.ToTable("clienteCompras");

                    b.HasData(
                        new
                        {
                            idCompra = 101,
                            cedula = "1002858874",
                            codigoCompra = "132789",
                            nombreCliente = "Sebastian Andrade",
                            valorCompra = "230"
                        },
                        new
                        {
                            idCompra = 102,
                            cedula = "1701286291",
                            codigoCompra = "146321",
                            nombreCliente = "Samantha Caicedo",
                            valorCompra = "189"
                        },
                        new
                        {
                            idCompra = 103,
                            cedula = "1700052132",
                            codigoCompra = "123579",
                            nombreCliente = "Darwin Hidrobo",
                            valorCompra = "365"
                        },
                        new
                        {
                            idCompra = 104,
                            cedula = "1702858866",
                            codigoCompra = "965412",
                            nombreCliente = "Kate Dittmer",
                            valorCompra = "210"
                        },
                        new
                        {
                            idCompra = 105,
                            cedula = "1742605671",
                            codigoCompra = "216546",
                            nombreCliente = "Juan Rosales",
                            valorCompra = "195"
                        });
                });

            modelBuilder.Entity("APIpetshop.Models.Contacto", b =>
                {
                    b.Property<int>("idContacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idContacto"));

                    b.Property<string>("cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idContacto");

                    b.ToTable("contactos");
                });

            modelBuilder.Entity("APIpetshop.Models.Producto", b =>
                {
                    b.Property<int>("idProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idProducto"));

                    b.Property<string>("codeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quantity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idProducto");

                    b.ToTable("productos");

                    b.HasData(
                        new
                        {
                            idProducto = 1001,
                            codeNumber = "watch001",
                            name = "Cool Watch",
                            picture = "watch.png",
                            price = "99",
                            quantity = "1"
                        },
                        new
                        {
                            idProducto = 1002,
                            codeNumber = "watch002",
                            name = "Diving Watch",
                            picture = "divingwatch.png",
                            price = "89",
                            quantity = "1"
                        },
                        new
                        {
                            idProducto = 1003,
                            codeNumber = "watch002",
                            name = "Dress Watch",
                            picture = "dresswatch.png",
                            price = "85",
                            quantity = "1"
                        },
                        new
                        {
                            idProducto = 1004,
                            codeNumber = "watch004",
                            name = "Military Watch",
                            picture = "militarywatch.png",
                            price = "99",
                            quantity = "1"
                        },
                        new
                        {
                            idProducto = 1005,
                            codeNumber = "watch004",
                            name = "Wrist Watch",
                            picture = "wristwatch.png",
                            price = "85",
                            quantity = "1"
                        },
                        new
                        {
                            idProducto = 1006,
                            codeNumber = "watch004",
                            name = "Army Watch",
                            picture = "awatch.png",
                            price = "99",
                            quantity = "1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
